spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #    oss配置
    alicloud:
      access-key: LTAI5tRvtCUJwgwVwknf4x82
      secret-key: I8HPDlPpA29vRzIdI2X6CUXjPBO9rI
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: lzgulimall